# Generated by Django 2.2.4 on 2019-09-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='songs',
            new_name='rated_songs',
        ),
    ]
