# Generated by Django 2.2.4 on 2019-09-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersong',
            unique_together={('user_of_song', 'song')},
        ),
    ]
